# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUI_EDITOR.ui'
##
## Created by: Qt User Interface Compiler version 6.2.4
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QMainWindow, QMenu,
    QMenuBar, QPlainTextEdit, QSizePolicy, QStatusBar,
    QWidget)

class Ui_MainWindow1(object):
    def setupUi(self, MainWindow1):
        if not MainWindow1.objectName():
            MainWindow1.setObjectName(u"MainWindow1")
        MainWindow1.resize(991, 583)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow1.sizePolicy().hasHeightForWidth())
        MainWindow1.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u"PLANET.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow1.setWindowIcon(icon)
        self.action1_1 = QAction(MainWindow1)
        self.action1_1.setObjectName(u"action1_1")
        self.action1_2 = QAction(MainWindow1)
        self.action1_2.setObjectName(u"action1_2")
        self.action1_3 = QAction(MainWindow1)
        self.action1_3.setObjectName(u"action1_3")
        self.action2_1 = QAction(MainWindow1)
        self.action2_1.setObjectName(u"action2_1")
        self.action2_2 = QAction(MainWindow1)
        self.action2_2.setObjectName(u"action2_2")
        self.action2_3 = QAction(MainWindow1)
        self.action2_3.setObjectName(u"action2_3")
        self.action1_4 = QAction(MainWindow1)
        self.action1_4.setObjectName(u"action1_4")
        self.action2_4 = QAction(MainWindow1)
        self.action2_4.setObjectName(u"action2_4")
        self.action3_1 = QAction(MainWindow1)
        self.action3_1.setObjectName(u"action3_1")
        self.action1_5 = QAction(MainWindow1)
        self.action1_5.setObjectName(u"action1_5")
        self.action2_5 = QAction(MainWindow1)
        self.action2_5.setObjectName(u"action2_5")
        self.action1_6 = QAction(MainWindow1)
        self.action1_6.setObjectName(u"action1_6")
        self.action2_6 = QAction(MainWindow1)
        self.action2_6.setObjectName(u"action2_6")
        self.action1_7 = QAction(MainWindow1)
        self.action1_7.setObjectName(u"action1_7")
        self.action1_7.setCheckable(True)
        self.action1_7.setChecked(True)
        self.action2_7 = QAction(MainWindow1)
        self.action2_7.setObjectName(u"action2_7")
        self.action2_7.setCheckable(True)
        self.action2_7.setChecked(True)
        self.action4_1 = QAction(MainWindow1)
        self.action4_1.setObjectName(u"action4_1")
        self.action4_2 = QAction(MainWindow1)
        self.action4_2.setObjectName(u"action4_2")
        self.centralwidget = QWidget(MainWindow1)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.plainTextEdit2 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit2.setObjectName(u"plainTextEdit2")
        font = QFont()
        font.setFamilies([u"\u6e38\u30b4\u30b7\u30c3\u30af"])
        font.setPointSize(18)
        self.plainTextEdit2.setFont(font)

        self.gridLayout.addWidget(self.plainTextEdit2, 0, 1, 1, 1)

        self.plainTextEdit1 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit1.setObjectName(u"plainTextEdit1")
        self.plainTextEdit1.setFont(font)

        self.gridLayout.addWidget(self.plainTextEdit1, 0, 0, 1, 1)

        MainWindow1.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow1)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 991, 22))
        self.menu1 = QMenu(self.menubar)
        self.menu1.setObjectName(u"menu1")
        self.menu2 = QMenu(self.menubar)
        self.menu2.setObjectName(u"menu2")
        self.menu3 = QMenu(self.menubar)
        self.menu3.setObjectName(u"menu3")
        self.menu4 = QMenu(self.menubar)
        self.menu4.setObjectName(u"menu4")
        MainWindow1.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow1)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow1.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu1.menuAction())
        self.menubar.addAction(self.menu2.menuAction())
        self.menubar.addAction(self.menu3.menuAction())
        self.menubar.addAction(self.menu4.menuAction())
        self.menu1.addAction(self.action1_1)
        self.menu1.addAction(self.action1_2)
        self.menu1.addAction(self.action1_3)
        self.menu1.addSeparator()
        self.menu1.addAction(self.action1_4)
        self.menu1.addSeparator()
        self.menu1.addAction(self.action1_5)
        self.menu1.addSeparator()
        self.menu1.addAction(self.action1_6)
        self.menu1.addAction(self.action1_7)
        self.menu2.addAction(self.action2_1)
        self.menu2.addAction(self.action2_2)
        self.menu2.addAction(self.action2_3)
        self.menu2.addSeparator()
        self.menu2.addAction(self.action2_4)
        self.menu2.addSeparator()
        self.menu2.addAction(self.action2_5)
        self.menu2.addSeparator()
        self.menu2.addAction(self.action2_6)
        self.menu2.addAction(self.action2_7)
        self.menu3.addAction(self.action3_1)
        self.menu4.addAction(self.action4_1)
        self.menu4.addSeparator()
        self.menu4.addAction(self.action4_2)

        self.retranslateUi(MainWindow1)

        QMetaObject.connectSlotsByName(MainWindow1)
    # setupUi

    def retranslateUi(self, MainWindow1):
        MainWindow1.setWindowTitle(QCoreApplication.translate("MainWindow1", u"NcWorks EDITOR", None))
        self.action1_1.setText(QCoreApplication.translate("MainWindow1", u"\u958b\u304f", None))
#if QT_CONFIG(shortcut)
        self.action1_1.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.action1_2.setText(QCoreApplication.translate("MainWindow1", u"\u4e0a\u66f8\u304d\u4fdd\u5b58", None))
#if QT_CONFIG(shortcut)
        self.action1_2.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+W", None))
#endif // QT_CONFIG(shortcut)
        self.action1_3.setText(QCoreApplication.translate("MainWindow1", u"\u540d\u524d\u3092\u4ed8\u3051\u3066\u4fdd\u5b58", None))
#if QT_CONFIG(shortcut)
        self.action1_3.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.action2_1.setText(QCoreApplication.translate("MainWindow1", u"\u958b\u304f", None))
#if QT_CONFIG(shortcut)
        self.action2_1.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.action2_2.setText(QCoreApplication.translate("MainWindow1", u"\u4e0a\u66f8\u304d\u4fdd\u5b58", None))
#if QT_CONFIG(shortcut)
        self.action2_2.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action2_3.setText(QCoreApplication.translate("MainWindow1", u"\u540d\u524d\u3092\u4ed8\u3051\u3066\u4fdd\u5b58", None))
#if QT_CONFIG(shortcut)
        self.action2_3.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.action1_4.setText(QCoreApplication.translate("MainWindow1", u"DXF\u30d5\u30a1\u30a4\u30eb\u3078\u5909\u63db", None))
#if QT_CONFIG(shortcut)
        self.action1_4.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.action2_4.setText(QCoreApplication.translate("MainWindow1", u"DXF\u30d5\u30a1\u30a4\u30eb\u3078\u5909\u63db", None))
#if QT_CONFIG(shortcut)
        self.action2_4.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.action3_1.setText(QCoreApplication.translate("MainWindow1", u"DXF\u30d5\u30a1\u30a4\u30eb\u3092\u30d7\u30ed\u30b0\u30e9\u30e0\u3078\u5909\u63db", None))
#if QT_CONFIG(shortcut)
        self.action3_1.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.action1_5.setText(QCoreApplication.translate("MainWindow1", u"\u6574\u5217", None))
#if QT_CONFIG(shortcut)
        self.action1_5.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.action2_5.setText(QCoreApplication.translate("MainWindow1", u"\u6574\u5217", None))
#if QT_CONFIG(shortcut)
        self.action2_5.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.action1_6.setText(QCoreApplication.translate("MainWindow1", u"\u30b7\u30df\u30e5\u30ec\u30fc\u30b7\u30e7\u30f3\u3092\u5b9f\u884c", None))
#if QT_CONFIG(shortcut)
        self.action1_6.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.action2_6.setText(QCoreApplication.translate("MainWindow1", u"\u30b7\u30df\u30e5\u30ec\u30fc\u30b7\u30e7\u30f3\u3092\u5b9f\u884c", None))
#if QT_CONFIG(shortcut)
        self.action2_6.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.action1_7.setText(QCoreApplication.translate("MainWindow1", u"\u30d7\u30ed\u30b0\u30e9\u30e0\u3092\u81ea\u52d5\u4fdd\u5b58\u3057\u3066\u30b7\u30df\u30e5\u30ec\u30fc\u30b7\u30e7\u30f3\u3092\u5b9f\u884c", None))
#if QT_CONFIG(shortcut)
        self.action1_7.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+U", None))
#endif // QT_CONFIG(shortcut)
        self.action2_7.setText(QCoreApplication.translate("MainWindow1", u"\u30d7\u30ed\u30b0\u30e9\u30e0\u3092\u81ea\u52d5\u4fdd\u5b58\u3057\u3066\u30b7\u30df\u30e5\u30ec\u30fc\u30b7\u30e7\u30f3\u3092\u5b9f\u884c", None))
#if QT_CONFIG(shortcut)
        self.action2_7.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+J", None))
#endif // QT_CONFIG(shortcut)
        self.action4_1.setText(QCoreApplication.translate("MainWindow1", u"NcWorks\u306b\u3064\u3044\u3066", None))
#if QT_CONFIG(shortcut)
        self.action4_1.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.action4_2.setText(QCoreApplication.translate("MainWindow1", u"\u30de\u30cb\u30e5\u30a2\u30eb", None))
#if QT_CONFIG(shortcut)
        self.action4_2.setShortcut(QCoreApplication.translate("MainWindow1", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.menu1.setTitle(QCoreApplication.translate("MainWindow1", u"\u30e1\u30a4\u30f3\u30d7\u30ed\u30b0\u30e9\u30e0\u306e\u7de8\u96c6", None))
        self.menu2.setTitle(QCoreApplication.translate("MainWindow1", u"\u30b5\u30d6\u30d7\u30ed\u30b0\u30e9\u30e0\u306e\u7de8\u96c6", None))
        self.menu3.setTitle(QCoreApplication.translate("MainWindow1", u"\u30c4\u30fc\u30eb", None))
        self.menu4.setTitle(QCoreApplication.translate("MainWindow1", u"\u30d8\u30eb\u30d7", None))
    # retranslateUi

