# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUI_SIM.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QFrame,
    QGraphicsView, QGridLayout, QGroupBox, QListWidget,
    QListWidgetItem, QMainWindow, QMenu, QMenuBar,
    QPlainTextEdit, QPushButton, QSizePolicy, QStatusBar,
    QWidget)

class Ui_MainWindow3(object):
    def setupUi(self, MainWindow3):
        if not MainWindow3.objectName():
            MainWindow3.setObjectName(u"MainWindow3")
        MainWindow3.resize(1346, 922)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow3.sizePolicy().hasHeightForWidth())
        MainWindow3.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u"PLANET.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow3.setWindowIcon(icon)
        self.action1_1 = QAction(MainWindow3)
        self.action1_1.setObjectName(u"action1_1")
        self.action2_1 = QAction(MainWindow3)
        self.action2_1.setObjectName(u"action2_1")
        self.action2_1.setEnabled(False)
        self.action2_2 = QAction(MainWindow3)
        self.action2_2.setObjectName(u"action2_2")
        self.action2_2.setCheckable(True)
        self.action2_2.setChecked(True)
        self.action1_2 = QAction(MainWindow3)
        self.action1_2.setObjectName(u"action1_2")
        self.action1_2.setEnabled(False)
        self.action1_3 = QAction(MainWindow3)
        self.action1_3.setObjectName(u"action1_3")
        self.action1_3.setEnabled(False)
        self.action2_3 = QAction(MainWindow3)
        self.action2_3.setObjectName(u"action2_3")
        self.action2_3.setCheckable(True)
        self.action2_4 = QAction(MainWindow3)
        self.action2_4.setObjectName(u"action2_4")
        self.action2_4.setCheckable(True)
        self.action2_4.setChecked(True)
        self.action2_5 = QAction(MainWindow3)
        self.action2_5.setObjectName(u"action2_5")
        self.action2_5.setCheckable(True)
        self.action2_6 = QAction(MainWindow3)
        self.action2_6.setObjectName(u"action2_6")
        self.action2_6.setCheckable(True)
        self.action2_6.setChecked(True)
        self.action3_1 = QAction(MainWindow3)
        self.action3_1.setObjectName(u"action3_1")
        self.action3_1.setCheckable(True)
        self.action3_2 = QAction(MainWindow3)
        self.action3_2.setObjectName(u"action3_2")
        self.action3_2.setCheckable(True)
        self.action3_3 = QAction(MainWindow3)
        self.action3_3.setObjectName(u"action3_3")
        self.action3_3.setCheckable(True)
        self.action3_4 = QAction(MainWindow3)
        self.action3_4.setObjectName(u"action3_4")
        self.action3_4.setCheckable(True)
        self.action3_4.setChecked(False)
        self.action2_7 = QAction(MainWindow3)
        self.action2_7.setObjectName(u"action2_7")
        self.action2_7.setCheckable(True)
        self.action2_8 = QAction(MainWindow3)
        self.action2_8.setObjectName(u"action2_8")
        self.action2_8.setCheckable(True)
        self.action2_8.setChecked(True)
        self.action3_5 = QAction(MainWindow3)
        self.action3_5.setObjectName(u"action3_5")
        self.action3_5.setCheckable(True)
        self.action3_6 = QAction(MainWindow3)
        self.action3_6.setObjectName(u"action3_6")
        self.action3_6.setCheckable(True)
        self.action3_6.setChecked(True)
        self.action2_9 = QAction(MainWindow3)
        self.action2_9.setObjectName(u"action2_9")
        self.action2_9.setCheckable(True)
        self.action2_9.setChecked(True)
        self.action2_9.setEnabled(False)
        self.action2_10 = QAction(MainWindow3)
        self.action2_10.setObjectName(u"action2_10")
        self.action2_10.setCheckable(True)
        self.action2_10.setChecked(False)
        self.action2_10.setEnabled(False)
        self.action2_11 = QAction(MainWindow3)
        self.action2_11.setObjectName(u"action2_11")
        self.action2_11.setCheckable(True)
        self.action2_11.setEnabled(False)
        self.action2_12 = QAction(MainWindow3)
        self.action2_12.setObjectName(u"action2_12")
        self.action2_12.setCheckable(True)
        self.action2_12.setEnabled(False)
        self.action2_13 = QAction(MainWindow3)
        self.action2_13.setObjectName(u"action2_13")
        self.action2_13.setCheckable(True)
        self.action2_14 = QAction(MainWindow3)
        self.action2_14.setObjectName(u"action2_14")
        self.action2_14.setCheckable(True)
        self.action2_14.setChecked(True)
        self.action2_14.setEnabled(False)
        self.action2_15 = QAction(MainWindow3)
        self.action2_15.setObjectName(u"action2_15")
        self.action2_15.setCheckable(True)
        self.action2_15.setChecked(True)
        self.action2_15.setEnabled(False)
        self.action2_16 = QAction(MainWindow3)
        self.action2_16.setObjectName(u"action2_16")
        self.action2_16.setCheckable(True)
        self.action2_16.setChecked(True)
        self.action2_16.setEnabled(False)
        self.action2_17 = QAction(MainWindow3)
        self.action2_17.setObjectName(u"action2_17")
        self.action2_17.setCheckable(True)
        self.action2_17.setChecked(True)
        self.action2_18 = QAction(MainWindow3)
        self.action2_18.setObjectName(u"action2_18")
        self.action2_18.setCheckable(True)
        self.action2_19 = QAction(MainWindow3)
        self.action2_19.setObjectName(u"action2_19")
        self.action2_19.setCheckable(True)
        self.action2_20 = QAction(MainWindow3)
        self.action2_20.setObjectName(u"action2_20")
        self.action2_20.setCheckable(True)
        self.action1_4 = QAction(MainWindow3)
        self.action1_4.setObjectName(u"action1_4")
        self.action1_5 = QAction(MainWindow3)
        self.action1_5.setObjectName(u"action1_5")
        self.action1_6 = QAction(MainWindow3)
        self.action1_6.setObjectName(u"action1_6")
        self.action4_1 = QAction(MainWindow3)
        self.action4_1.setObjectName(u"action4_1")
        self.action2_21 = QAction(MainWindow3)
        self.action2_21.setObjectName(u"action2_21")
        self.action2_21.setCheckable(True)
        self.action2_21.setChecked(False)
        self.action2_21.setEnabled(False)
        self.action2_22 = QAction(MainWindow3)
        self.action2_22.setObjectName(u"action2_22")
        self.action2_22.setCheckable(True)
        self.action2_22.setEnabled(False)
        self.action2_23 = QAction(MainWindow3)
        self.action2_23.setObjectName(u"action2_23")
        self.action2_23.setCheckable(True)
        self.action2_23.setChecked(True)
        self.action2_23.setEnabled(False)
        self.action2_24 = QAction(MainWindow3)
        self.action2_24.setObjectName(u"action2_24")
        self.action2_24.setCheckable(True)
        self.action2_25 = QAction(MainWindow3)
        self.action2_25.setObjectName(u"action2_25")
        self.action2_25.setCheckable(True)
        self.action1_7 = QAction(MainWindow3)
        self.action1_7.setObjectName(u"action1_7")
        self.centralwidget = QWidget(MainWindow3)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.graphicsView1 = QGraphicsView(self.centralwidget)
        self.graphicsView1.setObjectName(u"graphicsView1")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.graphicsView1.sizePolicy().hasHeightForWidth())
        self.graphicsView1.setSizePolicy(sizePolicy1)
        self.graphicsView1.setMouseTracking(False)
        self.graphicsView1.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.graphicsView1.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.BrushStyle.NoBrush)
        self.graphicsView1.setBackgroundBrush(brush)
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.BrushStyle.NoBrush)
        self.graphicsView1.setForegroundBrush(brush1)
        self.graphicsView1.setTransformationAnchor(QGraphicsView.ViewportAnchor.AnchorViewCenter)
        self.graphicsView1.setResizeAnchor(QGraphicsView.ViewportAnchor.NoAnchor)
        self.graphicsView1.setViewportUpdateMode(QGraphicsView.ViewportUpdateMode.MinimalViewportUpdate)

        self.gridLayout.addWidget(self.graphicsView1, 0, 1, 4, 1)

        self.listWidget1 = QListWidget(self.centralwidget)
        self.listWidget1.setObjectName(u"listWidget1")
        self.listWidget1.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.listWidget1.sizePolicy().hasHeightForWidth())
        self.listWidget1.setSizePolicy(sizePolicy2)
        self.listWidget1.setMinimumSize(QSize(300, 250))
        self.listWidget1.setMaximumSize(QSize(300, 16777215))
        font = QFont()
        font.setFamilies([u"\uff2d\uff33 \u30b4\u30b7\u30c3\u30af"])
        font.setPointSize(13)
        self.listWidget1.setFont(font)
        self.listWidget1.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)

        self.gridLayout.addWidget(self.listWidget1, 0, 0, 1, 1)

        self.groupBox_1 = QGroupBox(self.centralwidget)
        self.groupBox_1.setObjectName(u"groupBox_1")
        sizePolicy2.setHeightForWidth(self.groupBox_1.sizePolicy().hasHeightForWidth())
        self.groupBox_1.setSizePolicy(sizePolicy2)
        self.groupBox_1.setMinimumSize(QSize(300, 141))
        self.groupBox_1.setMaximumSize(QSize(300, 141))
        self.pushButton1 = QPushButton(self.groupBox_1)
        self.pushButton1.setObjectName(u"pushButton1")
        self.pushButton1.setEnabled(False)
        self.pushButton1.setGeometry(QRect(10, 20, 141, 31))
        self.pushButton2 = QPushButton(self.groupBox_1)
        self.pushButton2.setObjectName(u"pushButton2")
        self.pushButton2.setEnabled(False)
        self.pushButton2.setGeometry(QRect(150, 20, 141, 31))
        self.pushButton3 = QPushButton(self.groupBox_1)
        self.pushButton3.setObjectName(u"pushButton3")
        self.pushButton3.setEnabled(False)
        self.pushButton3.setGeometry(QRect(10, 60, 141, 31))
        self.pushButton4 = QPushButton(self.groupBox_1)
        self.pushButton4.setObjectName(u"pushButton4")
        self.pushButton4.setEnabled(False)
        self.pushButton4.setGeometry(QRect(150, 60, 141, 31))
        self.checkBox1 = QCheckBox(self.groupBox_1)
        self.checkBox1.setObjectName(u"checkBox1")
        self.checkBox1.setEnabled(True)
        self.checkBox1.setGeometry(QRect(160, 100, 101, 16))
        self.pushButton5 = QPushButton(self.groupBox_1)
        self.pushButton5.setObjectName(u"pushButton5")
        self.pushButton5.setEnabled(True)
        self.pushButton5.setGeometry(QRect(10, 100, 141, 31))

        self.gridLayout.addWidget(self.groupBox_1, 3, 0, 1, 1)

        self.listWidget2 = QListWidget(self.centralwidget)
        self.listWidget2.setObjectName(u"listWidget2")
        self.listWidget2.setEnabled(False)
        self.listWidget2.setMinimumSize(QSize(300, 141))
        self.listWidget2.setMaximumSize(QSize(300, 141))
        self.listWidget2.setFont(font)

        self.gridLayout.addWidget(self.listWidget2, 1, 0, 1, 1)

        self.plainTextEdit1 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit1.setObjectName(u"plainTextEdit1")
        self.plainTextEdit1.setMinimumSize(QSize(300, 300))
        self.plainTextEdit1.setMaximumSize(QSize(300, 300))
        self.plainTextEdit1.setFont(font)
        self.plainTextEdit1.setFrameShape(QFrame.Shape.Box)
        self.plainTextEdit1.setReadOnly(True)

        self.gridLayout.addWidget(self.plainTextEdit1, 2, 0, 1, 1)

        MainWindow3.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow3)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow3.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow3)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1346, 33))
        self.menu_1 = QMenu(self.menubar)
        self.menu_1.setObjectName(u"menu_1")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu4 = QMenu(self.menubar)
        self.menu4.setObjectName(u"menu4")
        MainWindow3.setMenuBar(self.menubar)

        self.menubar.addAction(self.menu_1.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu4.menuAction())
        self.menu_1.addAction(self.action1_2)
        self.menu_1.addAction(self.action1_3)
        self.menu_1.addSeparator()
        self.menu_1.addAction(self.action1_4)
        self.menu_1.addAction(self.action1_5)
        self.menu_1.addAction(self.action1_6)
        self.menu_1.addSeparator()
        self.menu_1.addAction(self.action1_7)
        self.menu_2.addAction(self.action2_1)
        self.menu_2.addAction(self.action2_6)
        self.menu_2.addAction(self.action2_13)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action2_5)
        self.menu_2.addAction(self.action2_15)
        self.menu_2.addAction(self.action2_9)
        self.menu_2.addAction(self.action2_18)
        self.menu_2.addAction(self.action2_19)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action2_17)
        self.menu_2.addAction(self.action2_2)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action2_25)
        self.menu_2.addAction(self.action2_3)
        self.menu_2.addAction(self.action2_4)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action2_24)
        self.menu_2.addAction(self.action2_7)
        self.menu_2.addAction(self.action2_8)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action2_23)
        self.menu_2.addAction(self.action2_22)
        self.menu_2.addAction(self.action2_21)
        self.menu_2.addAction(self.action2_10)
        self.menu_2.addAction(self.action2_11)
        self.menu_2.addAction(self.action2_12)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action2_14)
        self.menu_2.addAction(self.action2_16)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action2_20)
        self.menu.addAction(self.action3_1)
        self.menu.addAction(self.action3_2)
        self.menu.addAction(self.action3_3)
        self.menu.addAction(self.action3_4)
        self.menu.addAction(self.action3_5)
        self.menu.addAction(self.action3_6)
        self.menu4.addAction(self.action4_1)

        self.retranslateUi(MainWindow3)

        QMetaObject.connectSlotsByName(MainWindow3)
    # setupUi

    def retranslateUi(self, MainWindow3):
        MainWindow3.setWindowTitle(QCoreApplication.translate("MainWindow3", u"NcWorks SIM", None))
        self.action1_1.setText(QCoreApplication.translate("MainWindow3", u"NC\u30d7\u30ed\u30b0\u30e9\u30e0\u3092\u958b\u304f", None))
#if QT_CONFIG(shortcut)
        self.action1_1.setShortcut(QCoreApplication.translate("MainWindow3", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.action2_1.setText(QCoreApplication.translate("MainWindow3", u"\u8868\u793a\u30ea\u30bb\u30c3\u30c8", None))
        self.action2_2.setText(QCoreApplication.translate("MainWindow3", u"\u5207\u524a\u5de5\u5177\u57fa\u6e96\u4f4d\u7f6e\u30de\u30fc\u30ab\u30fc\u3092\u8868\u793a", None))
        self.action1_2.setText(QCoreApplication.translate("MainWindow3", u"\u5de5\u5177\u30c7\u30fc\u30bf\u3092\u958b\u304f", None))
        self.action1_3.setText(QCoreApplication.translate("MainWindow3", u"\u5de5\u5177\u30c7\u30fc\u30bf\u3092\u4fdd\u5b58", None))
        self.action2_3.setText(QCoreApplication.translate("MainWindow3", u"\u30d7\u30ed\u30b0\u30e9\u30e0\u8ecc\u8de1\u3092\u5168\u8868\u793a", None))
        self.action2_4.setText(QCoreApplication.translate("MainWindow3", u"\u30d7\u30ed\u30b0\u30e9\u30e0\u8ecc\u8de1\u3092\u500b\u5225\u8868\u793a", None))
        self.action2_5.setText(QCoreApplication.translate("MainWindow3", u"\u4e21\u5074\u8868\u793a", None))
        self.action2_6.setText(QCoreApplication.translate("MainWindow3", u"G\uff15\uff10\u6709\u52b9", None))
        self.action3_1.setText(QCoreApplication.translate("MainWindow3", u"\uff58\uff11", None))
        self.action3_2.setText(QCoreApplication.translate("MainWindow3", u"\uff58\uff12", None))
        self.action3_3.setText(QCoreApplication.translate("MainWindow3", u"\uff58\uff14", None))
        self.action3_4.setText(QCoreApplication.translate("MainWindow3", u"\uff58\uff18", None))
        self.action2_7.setText(QCoreApplication.translate("MainWindow3", u"\u30d7\u30ed\u30b0\u30e9\u30e0\u3092\u5168\u8868\u793a", None))
        self.action2_8.setText(QCoreApplication.translate("MainWindow3", u"\u30d7\u30ed\u30b0\u30e9\u30e0\u3092\u500b\u5225\u8868\u793a", None))
        self.action3_5.setText(QCoreApplication.translate("MainWindow3", u"\uff58\uff11\uff16", None))
        self.action3_6.setText(QCoreApplication.translate("MainWindow3", u"\u30d5\u30eb\u30b9\u30d4\u30fc\u30c9", None))
        self.action2_9.setText(QCoreApplication.translate("MainWindow3", u"\u30ac\u30a4\u30c9\u30d6\u30c3\u30b7\u30e5\u3092\u8868\u793a", None))
        self.action2_10.setText(QCoreApplication.translate("MainWindow3", u"\u30d5\u30a9\u30f3\u30c8\u30b5\u30a4\u30ba\u3000\uff11\uff15", None))
        self.action2_11.setText(QCoreApplication.translate("MainWindow3", u"\u30d5\u30a9\u30f3\u30c8\u30b5\u30a4\u30ba\u3000\uff12\uff10", None))
        self.action2_12.setText(QCoreApplication.translate("MainWindow3", u"\u30d5\u30a9\u30f3\u30c8\u30b5\u30a4\u30ba\u3000\uff12\uff15", None))
        self.action2_13.setText(QCoreApplication.translate("MainWindow3", u"\u30d7\u30ed\u30b0\u30e9\u30e0\u5ea7\u6a19\u3092\u57fa\u6e96\u306b\u79fb\u52d5", None))
        self.action2_14.setText(QCoreApplication.translate("MainWindow3", u"\u30d7\u30ed\u30b0\u30e9\u30e0\u306e\u8a73\u7d30\u3092\u8868\u793a", None))
        self.action2_15.setText(QCoreApplication.translate("MainWindow3", u"\u4e2d\u5fc3\u7dda\u3092\u8868\u793a", None))
        self.action2_16.setText(QCoreApplication.translate("MainWindow3", u"\u79fb\u52d5\u5148\u306e\u30d7\u30ed\u30b0\u30e9\u30e0\u3092\u62e1\u5927\u8868\u793a", None))
        self.action2_17.setText(QCoreApplication.translate("MainWindow3", u"\u30d7\u30ed\u30b0\u30e9\u30e0\u5ea7\u6a19\u30de\u30fc\u30ab\u30fc\u3092\u8868\u793a", None))
        self.action2_18.setText(QCoreApplication.translate("MainWindow3", u"\u30ac\u30a4\u30c9\u30d6\u30c3\u30b7\u30e5\u3092\u534a\u900f\u660e\u8868\u793a", None))
        self.action2_19.setText(QCoreApplication.translate("MainWindow3", u"\u5207\u524a\u5de5\u5177\u3092\u534a\u900f\u660e\u8868\u793a", None))
        self.action2_20.setText(QCoreApplication.translate("MainWindow3", u"\u30d7\u30ed\u30b0\u30e9\u30e0\u3092\u79fb\u52d5\u53ef\u80fd\u306b\u3059\u308b", None))
        self.action1_4.setText(QCoreApplication.translate("MainWindow3", u"\u5de5\u5177\u8ecc\u8de1\u3092DXF\u3068\u3057\u3066\u4fdd\u5b58\uff08\u534a\u5f84\uff09", None))
        self.action1_5.setText(QCoreApplication.translate("MainWindow3", u"\u5de5\u5177\u8ecc\u8de1\u3092DXF\u3068\u3057\u3066\u4fdd\u5b58\uff08\u76f4\u5f84\uff09", None))
        self.action1_6.setText(QCoreApplication.translate("MainWindow3", u"\u5de5\u5177\u8ecc\u8de1\u3092DXF\u3068\u3057\u3066\u4fdd\u5b58\uff08\u76f4\u5f84\u3000\u5168\u5225\u30ec\u30a4\u30e4\uff09", None))
        self.action4_1.setText(QCoreApplication.translate("MainWindow3", u"\u753b\u50cf\u3068\u3057\u3066\u4fdd\u5b58", None))
        self.action2_21.setText(QCoreApplication.translate("MainWindow3", u"\u30d5\u30a9\u30f3\u30c8\u30b5\u30a4\u30ba\u3000\uff11\uff10", None))
        self.action2_22.setText(QCoreApplication.translate("MainWindow3", u"\u30d5\u30a9\u30f3\u30c8\u30b5\u30a4\u30ba\u3000\uff15", None))
        self.action2_23.setText(QCoreApplication.translate("MainWindow3", u"\u30d5\u30a9\u30f3\u30c8\u30b5\u30a4\u30ba\u3000\uff11", None))
        self.action2_24.setText(QCoreApplication.translate("MainWindow3", u"\u30d7\u30ed\u30b0\u30e9\u30e0\u3092\u975e\u8868\u793a", None))
        self.action2_25.setText(QCoreApplication.translate("MainWindow3", u"\u30d7\u30ed\u30b0\u30e9\u30e0\u8ecc\u8de1\u3092\u975e\u8868\u793a", None))
        self.action1_7.setText(QCoreApplication.translate("MainWindow3", u"\u5de5\u5177\u30d5\u30a9\u30eb\u30c0\u3092\u8a18\u61b6", None))
        self.groupBox_1.setTitle(QCoreApplication.translate("MainWindow3", u"\u30b3\u30f3\u30c8\u30ed\u30fc\u30eb\u30dc\u30c3\u30af\u30b9", None))
        self.pushButton1.setText(QCoreApplication.translate("MainWindow3", u"\u958b\u59cb", None))
        self.pushButton2.setText(QCoreApplication.translate("MainWindow3", u"\u505c\u6b62", None))
        self.pushButton3.setText(QCoreApplication.translate("MainWindow3", u"\u524d\u3078", None))
        self.pushButton4.setText(QCoreApplication.translate("MainWindow3", u"\u6b21\u3078", None))
        self.checkBox1.setText(QCoreApplication.translate("MainWindow3", u"\u30b7\u30f3\u30b0\u30eb\u30d6\u30ed\u30c3\u30af", None))
        self.pushButton5.setText(QCoreApplication.translate("MainWindow3", u"\u6750\u6599\u5f84\u6307\u5b9a", None))
        self.menu_1.setTitle(QCoreApplication.translate("MainWindow3", u"\u30d5\u30a1\u30a4\u30eb", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow3", u"\u8868\u793a", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow3", u"\u5b9f\u884c\u30b9\u30d4\u30fc\u30c9", None))
        self.menu4.setTitle(QCoreApplication.translate("MainWindow3", u"\u7de8\u96c6", None))
    # retranslateUi

